#pragma once
#include <stdlib.h>
/* Machine generated by gen_authors.sh */
static const char *brisk_developers[] = {
        "Adam Hobaugh <adam@hobaugh.us>",
        "Daniel Greenwood <com64@0x64.ca>",
        "Eric Turgeon <4249848+ericbsd@users.noreply.github.com>",
        "Federico Damián Schonborn <federicodamiansch@gmail.com>",
        "gabrc52 <gabrc52@gmail.com>",
        "gabrielfin <gabrielfinkelstein@gmail.com>",
        "Ikey Doherty <ikey@solus-project.com>",
        "Joshua Strobl <JoshStrobl@users.noreply.github.com>",
        "Kim Malmo <berencamlost@msn.com>",
        "Martin Wimpress <code@flexion.org>",
        "Mike Gabriel <mike.gabriel@das-netzwerkteam.de>",
        "Pierre-Yves <pyu@riseup.net>",
        "raveit65 <mate@raveit.de>",
        "Staudey <Staudi.Kaos@gmail.com>",
        "Stefan Ric <stefan@solus-project.com>",
        "Stefan Ric <stfric369@gmail.com>",
        "Victor Kareh <vkareh@vkareh.net>",
        NULL,
};
